version: "3.7"

services:
  product:
    build: ./microservices/product
    ports:
      - "8080:8080"
    environment:
      - monster=energy

  transaction:
    build: ./microservices/transaction
    ports:
      - "8081:8080"

  user:
    build: ./microservices/user
    ports:
      - "8082:8080"

  postgresql:
    build: ./db/PostgreSQL
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
      - "POSTGRES_DB=docker"

  